### ISSUE TITLE
Apply more granular checks before triggering actions in CI

### ISSUE THREAD

**Issue by samayer12** [defenseunicorns/uds-core#628] opened 2024-08-01 20:49 UTC
### Describe what should be investigated or refactored

The CI/CD pipeline runs around 17 unique checks for all PRs with the existing conditional logic.
In some cases (e.g., updating a `.md` documentation file) it is probably not necessary to run all 17 checks.

For example, we may choose to skip running tests on PRs that only change `.md` files.
This could encourage contributors focused on just documentation updates to be more active.

For an even faster feedback loop, we can consider using more granular trigger rules in GitHub actions.

### Links to any relevant code

* [dorny/paths-filter](https://github.com/dorny/paths-filter)
* Current implementation of conditional checks: [pull-request-conditionals.yaml](https://github.com/defenseunicorns/uds-core/blob/main/.github/workflows/pull-request-conditionals.yaml)
* Filters are defined in [filters.yaml](https://github.com/defenseunicorns/uds-core/blob/main/.github/filters.yaml)

### Additional context

This is a good issue to work on so that you become familiar with how the `uds-core` CI/CD pipeline is configured.

**Comment by mjnagel** [comment] 2024-08-01 20:52
This is a duplicate of/related to https://github.com/defenseunicorns/uds-core/issues/589 - although this could be a broader evaluation of other (non-docs) places where we could filter things. To pass the required PR checks we will have to make sure that there are "shim" workflows for any checks.

**Closed as completed** 2024-08-29 15:49 UTC
Labels: ci
